# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "0X0FF.INFO (EN)"
email: "0x0ff.info@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  This is the english version of 0x0ff.info french blog.
  It's all about InfoSec, Beers and sometime cynical opinions.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "0x0ffinfo"
github_username:  "0x0ff"

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#

# Custom
remote_theme: "mmistakes/minimal-mistakes"
include: ["_pages"]
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "en-US"
subtitle: "(but in english)"
Name: "0x0ff.info"
#url:""
repository: "0x0ff/0x0ff.info"
head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
teaser: "/assets/images/default_teaser_0x0ff.png"
logo: "/assets/images/logo_0x0ff.png"
masthead_title: "0X0FF.INFO"
search: true
#breadcrumbs: false
#words_per_minute: 250
paginate: 5
Timezone: Europe/Paris
  
comments:
  provider: "disqus"
  disqus:
    shortname: "0x0ff"

social:
  type: "Person" # Person or Organization (defaults to Person)
  name: "0x0ff"  # If the user or organization name differs from the site's name
  links:
    - "https://twitter.com/0x0ffinfo"
    - "https://www.facebook.com/0x0ffinfo"
    - "https://www.root-me.org/0x0ff-info"
    - "https://www.newbiecontest.org/index.php?page=info_membre&id=67472"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-KJT5ZC8ELL"
    anonymize_ip: false # default

author:
  #name     : "0x0ff"
  avatar   : "/assets/images/bio-photo.png"
  #bio      : "I'm."
  #location : "Somewhere, World"
  links    :
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:0x0ffinfo@gmail.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/0x0ffinfo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/0x0ff"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://www.facebook.com/0x0ffinfo"
    - label: "Newbie-Contest"
      icon: "fas fa-fw fa-book"
      url: "https://www.newbiecontest.org/index.php?page=info_membre&id=67472"
    - label: "Root-Me"
      icon: "fas fa-fw fa-key"
      url: "https://www.root-me.org/0x0ff-info"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/0x0ffinfo"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/0x0ff"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
      sidebar:
        nav: "myside"
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
